### ISSUE TITLE
Backoffice almaPage.css breaks switchs in Prestashop 8.1+

### ISSUE THREAD

**Issue by gross-nvs** [alma/alma-installments-prestashop#269]
Hello,

The following rule in `admin/almaPage.css` break legacy switch rendering in PS 8.1+

```css
.bootstrap .prestashop-switch .slide-button::after {
    top: 49%;
}
```
Example in search parameters
![image](https://github.com/alma/alma-installments-prestashop/assets/48470278/6a594cd9-dea0-49e9-aa05-73434497dd36)
